config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  resources :products
  resource :admin, only: [:show], controller: :admin
  devise_for :users
  root "products#index"
  resources :products do
    resources :subscribers, only: [ :create ]
    resource :buy_now, only: [:show, :create], controller: :buy_now do 
      get "success", on: :collection
    end
  end
  resource :unsubscribe, only: [ :show ]
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
    include Notifications

    has_many :subscribers, dependent: :destroy
    has_one_attached :featured_image
    has_rich_text :description
    validates :name, presence: true
    validates :inventory_count, numericality: {greater_than_or_equal_to: 0}
    validates :price, numericality: {greater_than: 0}

    after_update_commit :notify_subscribers, if: :back_in_stock?

end

app/models/product/notifications.rb
module Product::Notifications
    extend ActiveSupport::Concern
  
    included do
      has_many :subscribers, dependent: :destroy
      after_update_commit :notify_subscribers, if: :back_in_stock?
    end
  
    def back_in_stock?
      inventory_count_previously_was == 0 && inventory_count > 0
    end
  
    def notify_subscribers
      subscribers.each do |subscriber|
        ProductMailer.with(product: self, subscriber: subscriber).in_stock.deliver_later
      end
    end
  end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  belongs_to :product
  generates_token_for :unsubscribe
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    before_action :authenticate_admin!
    def show_admin
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  around_action :switch_locale

  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end
end

app/controllers/buy_now_controller.rb
class BuyNowController < ApplicationController
    before_action :set_product
    def show; end
  
    def create
      session = Stripe::Checkout::Session.create({
        ui_mode: 'embedded',
        line_items: [{
            # Provide the exact Price ID (e.g. pr_1234) of the product you want to sell
            price_data: {
              currency: "usd",
              unit_amount: (@product.price * 100).to_i,
              product_data: {
                name: @product.name
              },
            },
            quantity: 1,
          }],
          shipping_address_collection: {
            allowed_countries: STRIPE_SUPPORTED_COUNTRIES
          },
          mode: 'payment',
          return_url: success_product_buy_now_url(@product),
      })
  
      render json: { client_secret: session.client_secret }
    end
  
    def success
    end
  
    private
  
    def set_product
      @product = Product.find(params[:product_id])
    end
  end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_admin!, except: %i[index show]
  before_action :set_product, only: %i[show edit update destroy]
  def index
    @products = Product.all
  end

  def show
  end
  
  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to @product
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  private
  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :featured_image, :inventory_count, :price)
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  before_action :set_product

  def create
    @product.subscribers.find_or_create_by(subscriber_params)
    redirect_to @product, notice: "You are now subscribed."
  end

  private

  def set_product
    @product = Product.find(params[:product_id])
  end

  def subscriber_params
    params.require(:subscriber).permit(:email)
  end
end

app/controllers/unsubscribes_controller.rb
class UnsubscribesController < ApplicationController
    before_action :set_subscriber
  
    def show
      @subscriber&.destroy
      redirect_to root_path, notice: "Unsubscribed successfully."
    end
  
    private
  
    def set_subscriber
      @subscriber = Subscriber.find_by_token_for(:unsubscribe, params[:token])
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/buy_now/show.html.erb
<p class="mb-4">
  <%= link_to "Back", product_path(@product), class: "text-blue-600 hover:text-blue-800 underline" %>
</p>

<div class="max-w-7xl w-full mx-auto px-10 mb-4 flex items-center space-x-4">
  <%= link_to "Products", products_path, class: "text-xl text-gray-100 hover:text-gray-200 font-medium" %>
  <span class="text-xl text-gray-100">/</span>
  <%= link_to @product.name, @product, class: "text-xl text-gray-100 font-bold" %>
</div>

<h1 class="text-3xl font-bold text-gray-900 mb-4"><%= @product.name %></h1>

<div class="mb-6">
  <%= image_tag @product.featured_image, alt: @product.name, class: "w-full max-w-md mx-auto rounded-lg shadow-lg" %>
</div>

<p class="text-lg text-gray-700 leading-relaxed mb-6"><%= @product.description %></p>

<div data-controller="stripe-checkout" data-stripe-checkout-url-value="<%= product_buy_now_path(@product) %>" class="mt-6">
</div>

app/views/buy_now/success.html.erb
<h1>Congrats!</h1>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Store" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://cdn.tailwindcss.com"></script>
    <%= javascript_importmap_tags %>
    <meta name="stripe-public-key" content="<%= Rails.application.credentials.dig(:stripe, :pk) %>">
    <script src="https://js.stripe.com/v3/"></script>
    <%= yield :head %>

  </head>

  <body>
    <div class="notice"><%= notice %></div>
    <main>
      <%= yield %>
    </main>  
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with model: product, class: "form-container" do |form| %>

  <div class="form-holder">
    <div class="input-group">
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, class: "form-input" %>
    </div>

    <div class="input-group">
      <%= form.label :description, class: "form-label" %>
      <%= form.rich_text_area :description, class: "form-input" %>
    </div>

    <div class="input-group">
      <%= form.label :featured_image, class: "form-label" %>
      <%= form.file_field :featured_image, accept: "image/*", class: "form-input" %>
    </div>

    <div class="input-group">
      <%= form.label :inventory_count, class: "form-label" %>
      <%= form.number_field :inventory_count, class: "form-input" %>
    </div>

    <div class="input-group">
      <%= form.label :price, class: "form-label" %>
      <%= form.number_field :price, step: :any, class: "form-input" %>
    </div>

    <div class="submit-btn-container">
      <%= form.submit "Save Product", class: "submit-btn" %>
    </div>
  
    <div class="actions-container">
      <%= link_to "Cancel", @product, class: "cancel-link" %>
    </div>
  </div>
<% end %>

app/views/products/_inventory.html.erb
<% if product.inventory_count? %>
  <p><%= product.inventory_count %> in stock</p>
<% else %>
  <p>Out of stock</p>
  <p>Email me when available.</p>

  <%= form_with model: [product, Subscriber.new] do |form| %>
    <%= form.email_field :email, placeholder: "you@example.com", required: true %>
    <%= form.submit "Submit" %>
  <% end %>
<% end %>

app/views/products/edit.html.erb
<h1 class="page-title">Edit Product</h1>

<div>
  <%= render "form", product: @product %>
</div>

app/views/products/index.html.erb
<h1 class="text-3xl font-bold text-center my-8">Welcome to Our Store</h1>

<div class="bg-white">
  <div class="py-16 sm:py-24 lg:mx-auto lg:max-w-7xl lg:px-8">
    <div class="flex items-center justify-between px-4 sm:px-6 lg:px-0">
      <h2 class="text-2xl font-bold tracking-tight text-gray-900">Trending Products</h2>
    </div>

    <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 xl:gap-x-8">
      <% @products.each do |product| %>
        <a href="<%= product_path(product) %>" class="group">
          <%= image_tag product.featured_image, alt: product.name, class: "aspect-square w-full rounded-lg bg-gray-200 object-cover group-hover:opacity-75 xl:aspect-[7/8]" %>
          <h3 class="mt-4 text-sm text-gray-700"><%= product.name %></h3>
          <p class="mt-1 text-lg font-medium text-gray-900"><%= number_to_currency(product.price) %></p>
        </a>
      <% end %>
    </div>
  </div>
</div>

<div class="mt-8 text-center">
  <% if admin_signed_in? %>
    <div class="mb-4">
      <p class="text-lg font-semibold text-gray-800">Welcome, <%= current_admin.email %>!</p>
    </div>
    <%= link_to "New Product", new_product_path, class: "inline-block px-4 py-2 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 transition duration-200" %>
    <%= button_to 'Logout', destroy_admin_session_path, method: :delete, class: "inline-block ml-4 px-4 py-2 bg-red-600 text-white font-semibold rounded-lg hover:bg-red-700 transition duration-200" %>
  <% elsif user_signed_in? %>
    <%= button_to "Log out", destroy_user_session_path, method: :delete, data: { turbo: false }, class: "inline-block px-4 py-2 bg-red-600 text-white font-semibold rounded-lg hover:bg-red-700 transition duration-200" %>
  <% else %>
    <%= link_to "Log in", new_user_registration_path, class: "inline-block px-4 py-2 bg-green-600 text-white font-semibold rounded-lg hover:bg-green-700 transition duration-200" %>
    <%= link_to "Sign up", new_user_registration_path, class: "inline-block ml-4 px-4 py-2 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 transition duration-200" %>
  <% end %>
</div>

app/views/products/new.html.erb
<h1 class="page-title">New product</h1>

<%= render "form", product: @product %>

app/views/products/show.html.erb
<div class="bg-white">
  <div class="button-back mb-4">
    <p>
      <%= link_to "Back", products_path, class: "text-indigo-600 hover:text-indigo-500 font-semibold" %>
    </p>
  </div>

  <section class="wrapper">
    <div class="max-w-7xl w-full mx-auto px-10 mb-2"> 
      <%= link_to "Products", products_path, class: "text-xl text-gray-900 hover:text-gray-600" %>
      <%= link_to "> #{@product.name}", @product, class: "text-xl text-gray-900" %>
    </div>

    <section class="product-img mb-6">
      <%= image_tag @product.featured_image, alt: @product.name, class: "rounded-lg shadow-md" %>
    </section>

    <section class="product-info">
      <% cache @product do %>
        <div class="product-text mb-4">
          <h1 class="text-2xl font-bold text-gray-900"><%= @product.name %></h1>
          <p class="mt-2 text-gray-700"><%= @product.description %></p>
          <p class="mt-2 text-lg font-medium text-gray-900"><%= number_to_currency @product.price %></p>
          <%= link_to "Buy Now", product_buy_now_path(@product), class: "mt-4 inline-block rounded-md bg-indigo-600 px-4 py-2 text-white font-semibold hover:bg-indigo-500" %>
          <%= render "inventory", product: @product %>
        </div>
      <% end %>

      <div class="product-price-btn">
        <% if admin_signed_in? %>
          <%= link_to "Edit", edit_product_path(@product), class: "inline-block rounded-md bg-blue-600 px-4 py-2 text-white font-semibold hover:bg-blue-500" %>
          <%= button_to "Delete", @product, method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "inline-block ml-4 rounded-md bg-red-600 px-4 py-2 text-white font-semibold hover:bg-red-500" %>
        <% end %>
      </div>
    </section>
  </section>
</div>